port: 8093

logger:
  level: DEBUG
tagger:
  url: http://localhost:8092/tag
accenter:
  url: http://klcdocker.vdu.lt/accenter/accent?human=true&roe=true&all=true  
transcriber:
  url: http://192.168.1.71:7027/transcription?gem=gem1&joinatsi=true&all=true
ipaConverter:
  url: http://127.0.0.1:8090/sampa2ipa_list
cliticsDetector:
  url: http://127.0.0.1:8091/clitics  
