port: 8093

logger:
  level: DEBUG
tagger:
  url: http://localhost:8092/tag
accenter:
  url: http://192.168.1.71:7021/accent?human=true&roe=true&all=true  
transcriber:
  url: http://192.168.1.71:7027/transcription?gem=gem1&joinatsi=true&all=true
ipaConverter:
  url: http://127.0.0.1:3000/sampa2ipa_list
cliticsDetector:
  url: http://127.0.0.1:8013/clitics  
