version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '3'
  driver: json-file

services:

  text-to-ipa:
    image: airenas/text-to-ipa:${SERVICE_VERSION}
    container_name: text-to-ip
    restart: unless-stopped
    logging: *default-logging
    environment:
      - LOGGER_LEVEL=DEBUG
      - TAGGER_URL=http://tagger:8000/tag
      - ACCENTER_URL=http://accenter:8000/accent?human=true&roe=true&all=true
      - TRANSCRIBER_URL=http://transcriber:8000/transcription?gem=gem1&joinatsi=true&all=true&skipvocalend=1&keepnb=1&hardNk=1&asimZdz=1&asimzdZ=1&asimZz=1&nogemaff=1
      - CLITICSDETECTOR_URL=http://clitics:8000/clitics
      - IPACONVERTER_URL=http://sampa-to-ipa:3000/sampa2ipa_list
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/text-transcriber/"
     - "traefik.port=8000"

  transcriber:
    container_name: transcriber
    image: airenas/transcriber:${TRANSCRIBER_SERVICE_VERSION}
    environment:
      - SECRET=${TRANSCRIBER_SECRET}
    restart: unless-stopped
    logging: *default-logging

  clitics:
    container_name: clitics  
    image: airenas/clitics:0.1.206
    environment:
      - SECRET=${CLITICS_SECRET}
    restart: unless-stopped
    logging: *default-logging  

  sampa-to-ipa:
    image: intelektikalt/sampa-to-ipa:${SAMPA_TO_IPA_SERVICE_VERSION}    
    restart: unless-stopped
    logging: *default-logging

networks:
  default:
    external:
      name: proxy_default # goes from proxy compose